version: '3'
services:
  flask_app:
    build: .
    container_name: flask_app
    expose:
      - "5000"
    networks:
      - webnet

  nginx:
    image: nginx:latest
    container_name: nginx_flask
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./certbot/www:/var/www/certbot
    networks:
      - webnet
    depends_on:
      - flask_app

networks:
  webnet:
