version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    networks:
      - webnet
    depends_on:
      - flask_app
    # Chỉ chạy Nginx ở chế độ HTTP (cho Certbot) trước
    command: /bin/sh -c "nginx -g 'daemon off;'"

  flask_app:
    build: .
    container_name: flask_app
    expose:
      - "5000"
    networks:
      - webnet
    depends_on:
      - nginx  # Flask sẽ chạy khi nginx sẵn sàng

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; certbot certonly --webroot --webroot-path=/var/www/certbot --email vnv1004@gmail.com --agree-tos --no-eff-email -d test.facevox.jp'"
    networks:
      - webnet

networks:
  webnet:
